apiVersion: v1
kind: Service
metadata:
  name: temporal-web-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: temporaltest
    app.kubernetes.io/name: temporal
  ports:
    - port: 8088
      targetPort: 8088