apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: temporal-greeting-worker
        image: temporal-greeting-worker:latest
        imagePullPolicy: Never