{{ if $.Values.server.workloadIdentity.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: {{ $.Values.server.workloadIdentity.googleServiceAccount }}
  name: {{ $.Values.server.workloadIdentity.serviceAccountName }}
  namespace: default
{{ end }}