server:
  sidecarContainers:
    - name: cloud-sql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.17
      command:
        - "/cloud_sql_proxy"
        - "-instances=prefab-atlas-338815:asia-southeast2:temporal-test=tcp:5432"
        - "-credential_file=/secret/temporal.json"
      securityContext:
        runAsNonRoot: true
      volumeMounts:
        - name: google-cloud-key
          mountPath: /secret/
          readOnly: true

  additionalVolumes:
    - name: google-cloud-key
      secret:
        secretName: temporal-secret

  workloadIdentity:
    enabled: false